name: PR message

on:
  # schedule:
  #   - cron: "0 0 2 * *"
  workflow_dispatch:
  # push:
  #   paths:
  #     - tests/**
  #     - churnobyl/**
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - name: Install libraries
        run: pip install pandas csv2md
      - name: Run program
        run: python pr_message.py >> $GITHUB_STEP_SUMMARY
