name: Prefect cloud run test

on: workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.5.3

        - name: Install
          run: pip install prefect
        - name: authenticate
          env:
            API_KEY: ${{secrets.PREFECT_API_KEY_GH}}
          run: |
            prefect auth login -k $API_KEY
            echo "Login completed"
